version: 2
jobs:
  build:
    working_directory: ~/website
    docker:
    - image: visualdensity/awscli:1.1
    steps:
    - checkout
    - run:
        name: List files
        command: ls -l ~/website
    - save_cache:
        key: firstsite-{{ .Revision }}
        paths:
          - ~/website
  staging:
    environment:
      TARGET_BUCKET: s3://sillyrandomsite.com
    working_directory: ~/website
    docker:
    - image: visualdensity/awscli:1.1
    steps:
    - restore_cache:
        keys: 
          - firstsite-{{ .Revision }}
    - run:
        name: List files
        command: ls -l ~/website
    - run:
        name: Pushing to S3
        command: _tools/deploy.sh -f
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - staging
